services:
  sonar-local:
    image: sonarqube:10.3-community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - 9000:9000
    expose:
      - 9000
    networks:
      - sonar
  jenkins-local:
    image: jenkins/jenkins:lts-jdk17
    volumes:
      - /Users/aferreres/projects/personal/jenkins:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    expose:
      - 8080
      - 50000
    networks:
      - sonar

networks:
  sonar:

volumes:
  sonarqube_data:
    external: false
  sonarqube_logs:
    external: false
  sonarqube_extensions:
    external: false

      
